#ifndef _X86_TRAP_H_
#define _X86_TRAP_H_

// https://github.com/mit-pdos/xv6-public

/* processor defined traps numbers : */
/** divide error */
#define T_DIVIDE		0
/** debug exception */
#define T_DEBUG			1
/** non-maskable interrupt */
#define T_NMI			2
/** breakpoint */
#define T_BRKPT			3
/** overflow */
#define T_OFLOW			4
/** bounds check */
#define T_BOUND			5
/** illegal opcode */
#define T_ILLOP			6
/** device not available */
#define T_DEVICE		7
/** double fault */
#define T_DBLFLT		8
/* reserved (not generated by recent processors) */
#define T_COPROC		9
/** invalid task switch segment */
#define T_TSS			10
/** segment not present */
#define T_SEGNP			11
/** stack exception */
#define T_STACK			12
/** general protection fault */
#define T_GPFLT			13
/** page fault */
#define T_PGFLT			14
/* reserved */
#define T_RES			15
/** floating point error */
#define T_FPERR			16
/** aligment check */
#define T_ALIGN			17
/** machine check */
#define T_MCHK			18
/** SIMD floating point error */
#define T_SIMDERR		19

#define T_IRQ0          32

#define IRQ_OFFSET 32
#define IRQ_TIMER        0
#define IRQ_KBD          1
#define IRQ_COM1         4
#define IRQ_COM2         3
#define IRQ_IDE         14
#define IRQ_ERROR       19
#define IRQ_SPURIOUS    31

#endif /* _X86_TRAP_H_ */
